apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.5.4-jdk-8-slim
      command: ['tail', '-f', '/dev/null']
      imagePullPolicy: Always
      resources:
        requests:
          memory: '500m'
          cpu: '500m'
        limits:
          memory: '1Gi'
          cpu: '500m'
    - name: docker
      image: docker:latest
      command: ['tail', '-f', '/dev/null']
      imagePullPolicy: Always
      resources:
        requests:
          memory: '500m'
          cpu: '500m'
        limits:
          memory: '1Gi'
          cpu: '500m'
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
