FROM node:14

RUN mkdir -p /opt/app

COPY yarn.lock /opt/app/yarn.lock
COPY package.json /opt/app/package.json

WORKDIR /opt/app
RUN yarn install

COPY . /opt/app
RUN NODE_ENV=production yarn build:api

EXPOSE 1337

CMD [ "node", "dist/apps/awesome-ac-api/main.js" ]