FROM node:14-slim AS build

COPY . /home/node/
WORKDIR /home/node/
RUN yarn install --frozen-lockfile && \
  yarn build:api
# RUN yarn build:api
# RUN yarn cache clean

FROM node:14-slim

USER node
EXPOSE 1337

WORKDIR /home/node/
COPY --from=build /home/node/dist/apps/awesome-ac-api ./dist/apps/awesome-ac-api
COPY --from=build /home/node/apps/awesome-ac-api ./apps/awesome-ac-api
COPY --from=build /home/node/node_modules ./node_modules

CMD [ "node", "dist/apps/awesome-ac-api/main.js" ]