version: 2.1

jobs:
  install:
    docker:
      - image: 'znck/pnpm:latest'
    steps:
      - checkout
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
            - '~/.pnpm-store'

  build_install:
    docker:
      - image: 'znck/pnpm:latest'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: install
          command: pnpm install
      - run:
          name: build
          command: pnpm run nx build awesome-ac

workflows:
  build_install:
    jobs:
      - install
      - build_install
