version: 2

cache:
  npm: false
  directories:
    - '~/.pnpm-store'
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store

jobs:
  build_install:
    docker:
      - image: 'circleci/node:14'
    steps:
      - checkout
      - run:
          name: install
          command: pnpm install
      - run:
          name: build
          command: pnpm run nx build awesome-ac

workflows:
  build_install:
    jobs:
      - build_install
