version: 2.1

jobs:
  docker_build:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: stiforr
          password: $DOCKER_PASS
    working_directory: ~/awesome-ac
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.13
      - restore_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: Docker login
          command: docker login -u stiforr -p $DOCKER_PASS
      - run:
          name: Build docker image
          command: docker build -t stiforr/awesome-ac:$CIRCLE_BRANCH .
      - run:
          name: Push docker Image
          command: docker push stiforr/awesome-ac:$CIRCLE_BRANCH
  checkout:
    docker:
      - image: 'circleci/node:14'
        auth:
          username: stiforr
          password: $DOCKER_PASS
    working_directory: ~/awesome-ac
    environment:
      CACHE_VERSION: v1
    steps:
      - checkout
      - save_cache:
          paths:
            - '~/awesome-ac'
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
  install_deps:
    docker:
      - image: 'circleci/node:14'
        auth:
          username: stiforr
          password: $DOCKER_PASS
    working_directory: ~/awesome-ac
    steps:
      - restore_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Cache
          paths:
            - '~/awesome-ac/.cache'
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
  build:
    docker:
      - image: 'circleci/node:14'
    working_directory: ~/awesome-ac
    steps:
      - restore_cache:
          name: Restore Yarn Cache
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: build
          command: yarn nx build awesome-ac

  end-to-end:
    docker:
      - image: 'cypress/base:14.15.0'
    working_directory: ~/awesome-ac
    steps:
      - restore_cache:
          name: Restore Yarn Cache
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: Run E2E Tests
          command: yarn nx e2e awesome-ac-e2e
  lint:
    docker:
      - image: 'circleci/node:14'
    working_directory: ~/awesome-ac
    steps:
      - restore_cache:
          name: Restore Yarn Cache
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: Lint code
          command: yarn nx lint awesome-ac
workflows:
  build_install:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
            - install_deps
      - install_deps:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
            - install_deps
      - end-to-end:
          requires:
            - checkout
            - install_deps
      - docker_build:
          requires:
            - checkout
            - build
            - install_deps
            - end-to-end
            - lint
          filters:
            tags:
              only: ^((([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$
