version: 2.1

jobs:
  install:
    docker:
      - image: 'circleci/node:14'
    steps:
      - checkout
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
            - '~/.pnpm-store'
      - run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - run: pnpm config set store-dir ~/.pnpm-store

  build_install:
    docker:
      - image: 'circleci/node:14'
    steps:
      - checkout
      - run:
          name: install
          command: pnpm install
      - run:
          name: build
          command: pnpm run nx build awesome-ac

workflows:
  build_install:
    jobs:
      - install
      - build_install
