version: 2.1

jobs:
  docker_build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.13
      - run:
          name: Build docker image
          command: docker build -t stiforr/awesome-ac:latest .
  build_install:
    docker:
      - image: 'circleci/node:14'
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: build
          command: yarn nx build awesome-ac
      - save_cache:
          name: Save Yarn Cache
          paths:
            - '~/.cache/yarn'
          key: dependency-cache-{{ checksum "yarn.lock" }}

workflows:
  build_install:
    jobs:
      - build_install
      - docker_build:
          requires:
            - build_install
