apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: stiforr/awesome-ac-api:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 1337
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: mongo-uri
                  name: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 1337
      targetPort: 1337
