---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: awesome-ac
  namespace: flux-system
spec:
  interval: 30s
  path: ./cluster
  prune: false
  sourceRef:
    kind: GitRepository
    name: app
  validation: client

